apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gke-pgk-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gke-pgk-app
    spec:
      containers:
      - name: gke-pgk-app
        image: dockleafdigital/gke-pgk-app
        ports:
        - containerPort: 9292